Views/Shared/Components/NavBar/NavBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoApplication.MVC.Views.Shared.Components.NavBar
{
    public class NavBarViewComponent : ViewComponent
    {
        public NavBarViewComponent()
        {

        }
        public IViewComponentResult Invoke() => View("Default");

    }
}

Views/Shared/Components/StatusMessages/StatusMessagesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoApplication.MVC.Views.Shared.Components.StatusMessages
{
    public class StatusMessagesViewComponent : ViewComponent
    {
        public StatusMessagesViewComponent()
        {

        }
        public IViewComponentResult Invoke() => View("Default");
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo Application</title>

    <environment include="Development">
        <link href="~/css/common.css" rel="stylesheet" />
        <link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/lib/jqueryui/jquery-ui.min.css" rel="stylesheet" />
        @*<link href="~/lib/datatables/css/jquery.dataTables.min.css" rel="stylesheet" />*@
        <link href="~/lib/datatables/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
        <link href="~/lib/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet" />
        <link href="~/lib/jquery-confirm/jquery-confirm.min.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/twitter-bootstrap/css/bootstrap.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"
              asp-fallback-href="~/lib/font-awesome/css/all.min.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link href="~/css/common.css" rel="stylesheet" asp-append-version="true" />
    </environment>
</head>

<body class="p-0">
    <header>
        <vc:Nav-Bar></vc:Nav-Bar>
    </header>
    <div role="main" class="flex-shrink-0">
        <div class="container-fluid body-content">
            <vc:status-messages></vc:status-messages>
            @RenderBody()
        </div>
    </div>
    <footer class="footer mt-auto py-3 text-center">
        <div class="container"><span class="text-muted">&copy; 2020 - Demo Application By Nandan Hegde</span></div>
    </footer>




    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
        <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
        <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
        <script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>
        <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
        <script src="~/lib/jquery-confirm/jquery-confirm.min.js"></script>
        <script src="~/lib/font-awesome/js/all.min.js"></script>
        <script type="text/javascript" src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/js/all.min.js"
                asp-fallback-src="~/lib/font-awesome/js/all.min.js"
                integrity="sha256-7zqZLiBDNbfN3W/5aEI1OX/5uvck9V0yhwKOA9Oe49M="
                crossorigin="anonymous">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @if (IsSectionDefined("Scripts"))
    {
        @RenderSection("Scripts", required: true)
    }
</body>
</html>